# Small makefile using the platformio cli library

.PHONY: test croquest #always execute the commands

default: croquest

test:
	pio run -e test -t upload

croquest:
	pio run -e croquest -t upload